# Generated by Django 4.1.1 on 2022-12-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=15)),
                ('book_name', models.CharField(max_length=15)),
                ('available_card', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('events_details', models.CharField(max_length=100)),
                ('events_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.CharField(max_length=15)),
                ('waiver_scheme', models.CharField(max_length=15)),
                ('tution_spfee', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=100)),
                ('fees_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Igoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('tenure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=15)),
                ('history', models.CharField(max_length=100)),
                ('fine', models.CharField(max_length=3)),
                ('cart', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Newcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=100)),
                ('card_image', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=15)),
                ('benefit', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igoal', models.CharField(max_length=100)),
                ('invite_earn', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('company_profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paylater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(max_length=100)),
                ('spend', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
                ('passbook', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('passout', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_dob', models.CharField(max_length=100)),
                ('nominee_relation', models.CharField(max_length=100)),
                ('nominee_address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_condition', models.CharField(max_length=100)),
                ('update', models.CharField(max_length=100)),
                ('help_support', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('dispute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Total_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('trans_mode', models.CharField(max_length=10)),
                ('merchant', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=100)),
                ('total_history', models.CharField(max_length=3)),
                ('reward_point', models.CharField(max_length=15)),
                ('cashback', models.CharField(max_length=15)),
                ('limit_transaction', models.CharField(max_length=15)),
                ('is_activate', models.CharField(max_length=15)),
                ('newcard_request', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
